name: danlish.com
favicon: null
layout_spectrum: 0.50279
typography_spectrum: 0.25511
title: danlish.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#1b0007'
    - '#ddd09b'
    - '#a99977'
    - '#756653'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
