name: danlish.com
favicon: null
layout_spectrum: 0.0031881474424153566
typography_spectrum: 0.2539354746695608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f6f5f1'
    - '#dc9b85'
    - '#8c81a9'
    - '#473f3d'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
