name: danlish.com
favicon: null
layout_spectrum: 0.75551
typography_spectrum: 0.501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#544d47'
    - '#fefefe'
    - '#958d82'
    - '#cfb896'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
