name: danlish.com
favicon: null
layout_spectrum: 0.75294
typography_spectrum: 0.50288
title: danlish.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c5c5c5'
    - '#2e2d2b'
    - '#b18f73'
    - '#ab5e24'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
